trigger:
- main

pool:
  name: 'Azure_DevOps_Demo'         # or whatever your agent pool is named
  demands: agent.name -equals Azure_DevOps_Demo


variables:
- group: FullstackVariables

stages:
- stage: Build
  jobs:
  - job: BuildFrontend
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
    - script: |
        cd client
        npm install
        npm run build
      displayName: 'Build Frontend App'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'client/dist'
        ArtifactName: 'frontend'
        publishLocation: 'Container'
